const genresArray = [
  { value: "рок", label: "рок" },
  { value: "поп-рок", label: "поп-рок" },
  { value: "альтернативний рок", label: "альтернативний рок" },
  { value: "класичний рок", label: "класичний рок" },
  { value: "фанк-рок", label: "фанк-рок" },
  { value: "сімфонічний рок", label: "сімфонічний рок" },
  { value: "рок-н-ролл", label: "рок-н-ролл" },
  { value: "електро-рок", label: "електро-рок" },
  { value: "етно-рок", label: "етно-рок" },
  { value: "панк-рок", label: "панк-рок" },
  { value: "поп-панк", label: "поп-панк" },
  { value: "психоделічний рок", label: "психоделічний рок" },
  { value: "інді-рок", label: "інді-рок" },
  { value: "хіп-хоп джаз", label: "хіп-хоп джаз" },
  { value: "фанк", label: "фанк" },
  { value: "бібоп", label: "бібоп" },
  { value: "біг-бенд", label: "біг-бенд" },
  { value: "свінг", label: "свінг" },
  { value: "босса-нова", label: "босса-нова" },
  { value: "самба", label: "самба" },
  { value: "румба", label: "румба" },
  { value: "чача", label: "чача" },
  { value: "регі", label: "регі" },
  { value: "ска", label: "ска" },
  { value: "мамба", label: "мамба" },
  { value: "афробіт", label: "афробіт" },
  { value: "фолк", label: "фолк" },
  { value: "афро-фолк", label: "афро-фолк" },
  { value: "академічна музика", label: "академічна музика" },
  { value: "симфонічна музика", label: "симфонічна музика" },
  { value: "опера", label: "опера" },
  { value: "кінематографічна музка", label: "кінематографічна музка" },
  { value: "треп", label: "треп" },
  { value: "реп", label: "реп" },
  { value: "хіп-хоп", label: "хіп-хоп" },
  { value: "фонк", label: "фонк" },
  { value: "думер-вейв", label: "думер-вейв" },
  { value: "вапор-вейв", label: "вапор-вейв" },
  { value: "техно", label: "техно" },
  { value: "хаус", label: "хаус" },
  { value: "edm", label: "edm" },
  { value: "r&b", label: "r&b" },
  { value: "соул", label: "соул" },
  { value: "діско", label: "діско" },
  { value: "поп", label: "поп" },
  { value: "денс", label: "денс" },
  { value: "лірична музика", label: "лірична музика" },
  { value: "дабстеп", label: "дабстеп" },
  { value: "драм н бейс", label: "драм н бейс" },
  { value: "джаз", label: "джаз" },
  { value: "кантрі", label: "кантрі" },
  { value: "фьюжн", label: "фьюжн" },
  { value: "математичний рок", label: "математичний рок" },
  { value: "госпел", label: "госпел" },
];
export default genresArray;
